[general]
import = [
  "github_dark_dark.toml",
  "bindings.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 1
[scrolling]
history = 5000

[window]
opacity = 0.0
dynamic_padding = false
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 12
y = 12

[keyboard]
