[user]
name = "Muhammad Fathurrohim"
email = "m.faturrohim13@gmail.com"

[signing]
backend = "gpg"
behavior = "keep"

[ui]
pager = "bat"
show-cryptographic-signatures = true

[git]
sign-on-push = true


#:schema https://jj-vcs.github.io/jj/latest/config-schema.json
